package adapters

import (
	"fmt"
	codefly "github.com/codefly-dev/sdk-go"
	"github.com/rs/cors"
)

/* -----------------------------------------------------------------

⚠️ This code is generated by the agent. Do not edit this file!

----------------------------------------------------------------- */

func Cors() *cors.Cors {
	if codefly.IsLocalEnvironment() {
		fmt.Println("setting up cors for local environment")
		return cors.New(cors.Options{
			AllowedOrigins: []string{"*"},
			AllowedMethods: []string{"GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"},
			AllowedHeaders: []string{"*"},
		})
	}
	return cors.New(cors.Options{
		AllowedOrigins: []string{"*"},
		AllowedMethods: []string{"GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"},
		AllowedHeaders: []string{"*"},
	})
}
