package adapters

/* -----------------------------------------------------------------

⚠️ This code is generated by the agent. Do not edit this file!

----------------------------------------------------------------- */

import (
	"codefly-base/pkg/gen"
	"codefly-base/pkg/gen/genconnect"
	"context"
	"fmt"
	"net/http"

	"connectrpc.com/connect"
	codefly "github.com/codefly-dev/sdk-go"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"
)

// ConnectServer serves the Connect, gRPC, and gRPC-Web protocols over HTTP.
// It handles all three protocols on a single port.
type ConnectServer struct {
	config *Configuration
}

func NewConnectServer(c *Configuration) (*ConnectServer, error) {
	return &ConnectServer{config: c}, nil
}

// connectHandler wraps the GrpcServer to implement the Connect handler interface.
type connectHandler struct{}

func (h *connectHandler) Version(ctx context.Context, req *connect.Request[gen.VersionRequest]) (*connect.Response[gen.VersionResponse], error) {
	return connect.NewResponse(&gen.VersionResponse{
		Version: codefly.ServiceVersion(),
	}), nil
}

func (s *ConnectServer) Run(ctx context.Context) error {
	if s.config.EndpointConnectPort == nil {
		return nil
	}
	port := *s.config.EndpointConnectPort
	fmt.Println("Starting Connect server at", port)

	mux := http.NewServeMux()

	// Register the Connect handler (serves Connect, gRPC, and gRPC-Web)
	path, handler := genconnect.NewWebServiceHandler(&connectHandler{})
	mux.Handle(path, handler)

	// Use h2c for HTTP/2 without TLS (development mode)
	server := &http.Server{
		Addr:    fmt.Sprintf(":%d", port),
		Handler: h2c.NewHandler(mux, &http2.Server{}),
	}

	return server.ListenAndServe()
}
