package adapters

import (
	"github.com/rs/cors"
)

/* -----------------------------------------------------------------

⚠️ This code is generated by the agent. Do not edit this file!

----------------------------------------------------------------- */

func Cors() *cors.Cors {
	return cors.New(cors.Options{
		AllowOriginFunc: func(string) bool { return false },
		AllowedMethods:  []string{"GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"},
	})
}
