package adapters

/* -----------------------------------------------------------------

⚠️ This code is generated by the agent. Do not edit this file!

Recommendation: create a `rpcs.go` file in the same directory as this file and
implement your APIs there.

----------------------------------------------------------------- */

import (
	"buf.build/go/protovalidate"
	gen "codefly-base/pkg/gen"
	"context"
	"fmt"
	"net"
	"net/http"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	"google.golang.org/protobuf/proto"

	"google.golang.org/grpc/reflection"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"

	codefly "github.com/codefly-dev/sdk-go"
	"google.golang.org/grpc"
	"google.golang.org/grpc/health"
	"google.golang.org/grpc/health/grpc_health_v1"
)

var validator protovalidate.Validator

func init() {
	v, err := protovalidate.New()
	if err != nil {
		panic(fmt.Errorf("failed to create validator: %w", err))
	}
	validator = v
}

func Validate(req proto.Message) error {
	err := validator.Validate(req)
	if err != nil {
		return status.Error(codes.InvalidArgument, err.Error())
	}
	return nil
}

func (s *GrpcServer) Version(ctx context.Context, req *gen.VersionRequest) (*gen.VersionResponse, error) {
	if err := Validate(req); err != nil {
		return nil, err
	}
	return &gen.VersionResponse{
		Version: codefly.ServiceVersion(),
	}, nil
}

type Configuration struct {
	EndpointGrpcPort    uint16
	EndpointHttpPort    *uint16
	EndpointConnectPort *uint16
	// GRPCServerOptions installs transport policy such as authentication,
	// authorization, telemetry, and rate limiting before the listener starts.
	GRPCServerOptions []grpc.ServerOption
	// Service replaces the generated Version-only implementation when the
	// service owns substantive RPCs with constructor-injected dependencies.
	Service gen.WebServiceServer
	// ServeMuxOptions are appended to the REST gateway mux's generated options.
	// A runtime.ServeMuxOption reaches a mux at construction only, and the
	// plugins.RegisterREST seam receives the mux already built, so this is the
	// one way in: a WithForwardResponseOption carrying an ETag and a
	// Cache-Control for one RPC, a header matcher, a marshaler.
	//
	// They are applied after the generated options, which decides what happens
	// to a conflict. An option that sets one value (WithErrorHandler, either
	// header matcher, WithMarshalerOption for a MIME type already registered)
	// replaces the generated default. An option that accumulates (WithMetadata,
	// WithForwardResponseOption) runs in addition to it, after it.
	ServeMuxOptions []runtime.ServeMuxOption
	// Routes are HTTP handlers served on the REST listener ahead of the gateway,
	// matched by path prefix, inside the CORS and logging wrappers. For a
	// protocol the gateway cannot carry — a Connect handler for a second
	// protobuf service, say, whose every method would otherwise need its own
	// gwMux.HandlePath template. First match wins, and a route is consulted
	// before every gateway path, /healthz included.
	//
	// What a mounted handler gets is this listener: HTTP/1.1, so a Connect or
	// gRPC-Web caller is served and a gRPC-over-h2c one is not — that is the
	// Connect listener connect-endpoint declares.
	Routes []Route
	// Middleware wrap the listener's handler chain, the first entry outermost,
	// inside the CORS policy and ahead of the routes and the gateway. For policy
	// that must see a request before anything reads its body: a request-body
	// bound (http.MaxBytesReader, or a 413 on a declared over-cap
	// Content-Length), a tracing span, a rate limit.
	//
	// Inside CORS so that what a middleware answers still carries the CORS
	// headers a browser needs to read it, and inside the generated request
	// logging so that it is recorded like any other outcome.
	Middleware []func(http.Handler) http.Handler
	// GatewayDialOptions are appended to the options the REST listener dials the
	// gRPC server with, for the gateway's hop and the health probe's client.
	// Where a service raises gRPC's 4 MiB default call bounds:
	// grpc.WithDefaultCallOptions(grpc.MaxCallRecvMsgSize(n), grpc.MaxCallSendMsgSize(n)).
	// A bound set only on the server leaves the proxy refusing the message the
	// server would have accepted.
	GatewayDialOptions []grpc.DialOption
}

type GrpcServer struct {
	gen.UnimplementedWebServiceServer
	configuration *Configuration
	gRPC          *grpc.Server
	health        *health.Server
	validator     protovalidate.Validator
}

func NewGrpServer(c *Configuration) (*GrpcServer, error) {
	grpcServer := grpc.NewServer(c.GRPCServerOptions...)
	v, err := protovalidate.New()
	if err != nil {
		return nil, fmt.Errorf("failed to create validator: %w", err)
	}

	healthServer := health.NewServer()
	grpc_health_v1.RegisterHealthServer(grpcServer, healthServer)
	healthServer.SetServingStatus("", grpc_health_v1.HealthCheckResponse_SERVING)
	healthServer.SetServingStatus(gen.WebService_ServiceDesc.ServiceName, grpc_health_v1.HealthCheckResponse_SERVING)

	s := GrpcServer{
		configuration: c,
		gRPC:          grpcServer,
		health:        healthServer,
		validator:     v,
	}
	service := gen.WebServiceServer(&s)
	if c.Service != nil {
		service = c.Service
	}
	gen.RegisterWebServiceServer(grpcServer, service)
	if codefly.IsLocal() {
		reflection.Register(grpcServer)
	}
	return &s, nil
}

func (s *GrpcServer) Run(ctx context.Context) error {
	fmt.Println("Starting gRPC server at", s.configuration.EndpointGrpcPort)
	lis, err := net.Listen("tcp", fmt.Sprintf(":%d", s.configuration.EndpointGrpcPort))
	if err != nil {
		return fmt.Errorf("failed to listen: %v", err)
	}

	if err := s.gRPC.Serve(lis); err != nil {
		return fmt.Errorf("failed to serve: %s", err)
	}
	return nil
}
