package adapters

/* -----------------------------------------------------------------

⚠️ This code is generated by the agent. Do not edit this file!

This file exposes selected gRPC unary RPCs as MCP tools. Everything is derived
from the protobuf descriptors compiled into the binary: each tool's JSON
Schema and the request/response marshaling. No per-RPC wrapper code is
generated — dispatch is a single generic gRPC invoke over a dynamic message.

Only the RPCs named in mcpAllowedMethods are exposed. The allowlist is the
final exposure gate: it is rendered from the service's mcp-methods setting and
an empty list exposes nothing.

----------------------------------------------------------------- */

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"

	codefly "github.com/codefly-dev/sdk-go"
	"github.com/modelcontextprotocol/go-sdk/mcp"
	"google.golang.org/grpc"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/reflect/protoregistry"
	"google.golang.org/protobuf/types/dynamicpb"
)

// MCPPath is the HTTP path the MCP Streamable HTTP endpoint is mounted at,
// riding the same listener as the REST gateway.
const MCPPath = "/mcp"

// mcpAllowedMethods is the explicit allowlist of unary RPCs exposed as MCP
// tools, each in "<package>.<Service>/<Method>" form. Only listed methods
// become tools; an empty list exposes nothing. Rendered from mcp-methods.
var mcpAllowedMethods = []string{
	"api.WebService/Version",
}

// MCPRouter dispatches MCPPath (and its subpaths) to the MCP handler and every
// other request to next. It intentionally does not use http.ServeMux, whose
// path cleaning and trailing-slash redirects would change the REST gateway's
// routing behavior for non-MCP paths.
func MCPRouter(mcpHandler, next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == MCPPath || strings.HasPrefix(r.URL.Path, MCPPath+"/") {
			mcpHandler.ServeHTTP(w, r)
			return
		}
		next.ServeHTTP(w, r)
	})
}

// NewMCPHandler builds the MCP Streamable HTTP handler. grpcConn dials the
// service's own in-process gRPC listener; tool calls are forwarded to it so
// protobuf validation, interceptors, and the real RPC implementation run
// exactly as they do for any other gRPC client. It returns an error if a
// configured tool cannot be built so the service fails loudly rather than
// serving a broken tool surface.
func NewMCPHandler(grpcConn grpc.ClientConnInterface) (http.Handler, error) {
	server, err := NewMCPServer(grpcConn)
	if err != nil {
		return nil, err
	}
	// CrossOriginProtection rejects browser cross-origin requests (Origin /
	// Sec-Fetch-Site mismatch), closing the DNS-rebinding / CSRF vector that a
	// mounted MCP endpoint would otherwise inherit from the permissive REST
	// CORS policy. Non-browser MCP clients send no Origin and are unaffected.
	opts := &mcp.StreamableHTTPOptions{
		CrossOriginProtection: http.NewCrossOriginProtection(),
	}
	return mcp.NewStreamableHTTPHandler(func(*http.Request) *mcp.Server { return server }, opts), nil
}

// NewMCPServer registers one MCP tool per allowlisted unary RPC. Selectors are
// resolved against the global protobuf registry, so RPCs from any compiled
// proto file are reachable regardless of filename. A selector that names a
// missing service or method is a configuration error and fails the build of
// the server. Streaming RPCs are skipped until MCP stream semantics are
// deliberately supported.
func NewMCPServer(grpcConn grpc.ClientConnInterface) (*mcp.Server, error) {
	server := mcp.NewServer(&mcp.Implementation{
		Name:    "codefly-base",
		Version: codefly.ServiceVersion(),
	}, nil)

	for _, selector := range mcpAllowedMethods {
		sd, md, err := resolveMethod(selector)
		if err != nil {
			return nil, err
		}
		if md.IsStreamingClient() || md.IsStreamingServer() {
			fmt.Printf("MCP: skipping streaming RPC %s (unary RPCs only)\n", selector)
			continue
		}

		schema, err := json.Marshal(messageSchema(md.Input(), map[protoreflect.FullName]bool{}))
		if err != nil {
			return nil, fmt.Errorf("MCP: cannot build schema for %s: %w", selector, err)
		}

		tool := &mcp.Tool{
			Name:        fmt.Sprintf("%s_%s", sd.Name(), md.Name()),
			Description: fmt.Sprintf("Invoke the %s gRPC method.", md.FullName()),
			InputSchema: json.RawMessage(schema),
		}
		fullMethod := fmt.Sprintf("/%s/%s", sd.FullName(), md.Name())
		server.AddTool(tool, mcpToolHandler(grpcConn, fullMethod, md.Input(), md.Output()))
	}
	return server, nil
}

// resolveMethod parses a "<package>.<Service>/<Method>" selector and looks the
// method up in the global protobuf registry.
func resolveMethod(selector string) (protoreflect.ServiceDescriptor, protoreflect.MethodDescriptor, error) {
	service, method, ok := strings.Cut(selector, "/")
	if !ok || service == "" || method == "" {
		return nil, nil, fmt.Errorf("MCP: malformed method selector %q (want \"package.Service/Method\")", selector)
	}
	desc, err := protoregistry.GlobalFiles.FindDescriptorByName(protoreflect.FullName(service))
	if err != nil {
		return nil, nil, fmt.Errorf("MCP: unknown service %q in selector %q: %w", service, selector, err)
	}
	sd, ok := desc.(protoreflect.ServiceDescriptor)
	if !ok {
		return nil, nil, fmt.Errorf("MCP: %q is not a service in selector %q", service, selector)
	}
	md := sd.Methods().ByName(protoreflect.Name(method))
	if md == nil {
		return nil, nil, fmt.Errorf("MCP: service %q has no method %q (selector %q)", service, method, selector)
	}
	return sd, md, nil
}

// mcpToolHandler converts MCP arguments into the RPC's protobuf request,
// invokes the unary RPC generically over the gRPC connection, and returns the
// protobuf response as MCP structured content. gRPC status failures are
// surfaced as model-readable tool errors rather than transport errors.
func mcpToolHandler(grpcConn grpc.ClientConnInterface, fullMethod string, input, output protoreflect.MessageDescriptor) mcp.ToolHandler {
	return func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		request := dynamicpb.NewMessage(input)
		if args := req.Params.Arguments; len(args) > 0 && string(args) != "null" {
			if err := protojson.Unmarshal(args, request); err != nil {
				return toolErrorf("invalid arguments: %v", err), nil
			}
		}

		response := dynamicpb.NewMessage(output)
		if err := grpcConn.Invoke(ctx, fullMethod, request, response); err != nil {
			return grpcToolError(err), nil
		}

		data, err := protojson.Marshal(response)
		if err != nil {
			return toolErrorf("cannot marshal response: %v", err), nil
		}
		var structured any
		if err := json.Unmarshal(data, &structured); err != nil {
			return toolErrorf("cannot decode response: %v", err), nil
		}
		return &mcp.CallToolResult{
			Content:           []mcp.Content{&mcp.TextContent{Text: string(data)}},
			StructuredContent: structured,
		}, nil
	}
}

// grpcToolError preserves the gRPC status code, message, and details as a
// readable MCP tool error.
func grpcToolError(err error) *mcp.CallToolResult {
	st := status.Convert(err)
	text := fmt.Sprintf("gRPC error %s: %s", st.Code(), st.Message())
	for _, detail := range st.Details() {
		text += fmt.Sprintf("\ndetail: %v", detail)
	}
	return toolError(text)
}

func toolErrorf(format string, args ...any) *mcp.CallToolResult {
	return toolError(fmt.Sprintf(format, args...))
}

func toolError(text string) *mcp.CallToolResult {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{&mcp.TextContent{Text: text}},
	}
}

// messageSchema builds a JSON Schema object for a protobuf message. seen
// guards against recursive message types: a message already being described
// on the current path is emitted as an open object rather than expanded
// forever.
func messageSchema(md protoreflect.MessageDescriptor, seen map[protoreflect.FullName]bool) map[string]any {
	if wk := wellKnownSchema(md); wk != nil {
		return wk
	}
	if seen[md.FullName()] {
		return map[string]any{"type": "object"}
	}
	seen[md.FullName()] = true
	defer delete(seen, md.FullName())

	properties := map[string]any{}
	fields := md.Fields()
	for i := 0; i < fields.Len(); i++ {
		fd := fields.Get(i)
		properties[fd.JSONName()] = fieldSchema(fd, seen)
	}
	schema := map[string]any{"type": "object"}
	if len(properties) > 0 {
		schema["properties"] = properties
	}
	return schema
}

// fieldSchema describes a single field, accounting for maps, repeated fields,
// and the underlying value kind.
func fieldSchema(fd protoreflect.FieldDescriptor, seen map[protoreflect.FullName]bool) map[string]any {
	if fd.IsMap() {
		return map[string]any{
			"type":                 "object",
			"additionalProperties": valueSchema(fd.MapValue(), seen),
		}
	}
	if fd.IsList() {
		return map[string]any{
			"type":  "array",
			"items": valueSchema(fd, seen),
		}
	}
	return valueSchema(fd, seen)
}

// valueSchema describes the scalar, enum, or message value carried by a field
// (ignoring list/map cardinality, which fieldSchema handles).
func valueSchema(fd protoreflect.FieldDescriptor, seen map[protoreflect.FullName]bool) map[string]any {
	switch fd.Kind() {
	case protoreflect.BoolKind:
		return map[string]any{"type": "boolean"}
	case protoreflect.StringKind:
		return map[string]any{"type": "string"}
	case protoreflect.BytesKind:
		// protojson encodes bytes as base64 strings.
		return map[string]any{"type": "string", "contentEncoding": "base64"}
	case protoreflect.FloatKind, protoreflect.DoubleKind:
		return map[string]any{"type": "number"}
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind,
		protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return map[string]any{"type": "integer"}
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind,
		protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		// protojson renders 64-bit integers as strings to avoid precision loss;
		// accept a JSON number too for convenience.
		return map[string]any{"type": []any{"string", "integer"}}
	case protoreflect.EnumKind:
		values := fd.Enum().Values()
		names := make([]any, 0, values.Len())
		for i := 0; i < values.Len(); i++ {
			names = append(names, string(values.Get(i).Name()))
		}
		return map[string]any{"type": "string", "enum": names}
	case protoreflect.MessageKind, protoreflect.GroupKind:
		return messageSchema(fd.Message(), seen)
	default:
		return map[string]any{}
	}
}

// wellKnownSchema maps the protobuf well-known types to their protojson
// representation. It returns nil for ordinary messages.
func wellKnownSchema(md protoreflect.MessageDescriptor) map[string]any {
	switch md.FullName() {
	case "google.protobuf.Timestamp", "google.protobuf.Duration", "google.protobuf.FieldMask":
		return map[string]any{"type": "string"}
	case "google.protobuf.Struct", "google.protobuf.Any", "google.protobuf.Empty":
		return map[string]any{"type": "object"}
	case "google.protobuf.ListValue":
		return map[string]any{"type": "array"}
	case "google.protobuf.Value":
		return map[string]any{}
	case "google.protobuf.BoolValue":
		return map[string]any{"type": "boolean"}
	case "google.protobuf.StringValue", "google.protobuf.BytesValue",
		"google.protobuf.Int64Value", "google.protobuf.UInt64Value":
		return map[string]any{"type": "string"}
	case "google.protobuf.Int32Value", "google.protobuf.UInt32Value":
		return map[string]any{"type": "integer"}
	case "google.protobuf.FloatValue", "google.protobuf.DoubleValue":
		return map[string]any{"type": "number"}
	default:
		return nil
	}
}
