package adapters

/* -----------------------------------------------------------------

⚠️ This code is generated by the agent. Do not edit this file!

----------------------------------------------------------------- */

import (
	"bytes"
	"codefly-base/pkg/gen"
	"codefly-base/plugins"
	"context"
	"fmt"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/status"
	"io"
	"net/http"
	"strings"

	"github.com/codefly-dev/core/wool"

	"google.golang.org/grpc/metadata"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/health/grpc_health_v1"
)

type RestServer struct {
	config *Configuration
	server *http.Server
}

func NewRestServer(c *Configuration) (*RestServer, error) {
	server := &RestServer{
		config: c,
		server: &http.Server{Addr: fmt.Sprintf(":%d", *c.EndpointHttpPort)},
	}
	// Start Rest server (and proxy calls to gRPC server endpoint)
	return server, nil
}

func CustomHeaderToGRPCMetadataAnnotator(ctx context.Context, req *http.Request) metadata.MD {
	return wool.MetadataFromRequest(ctx, req)
}

func customErrorHandler(ctx context.Context, mux *runtime.ServeMux, marshaler runtime.Marshaler, w http.ResponseWriter, r *http.Request, err error) {
	// Check if it's a "not found" error
	if runtime.HTTPStatusFromCode(status.Code(err)) == http.StatusNotFound {
		http.Error(w, "Route not found", http.StatusNotFound)
		return
	}

	// For other errors, use the default error handler
	runtime.DefaultHTTPErrorHandler(ctx, mux, marshaler, w, r, err)
}

// gatewayMuxOptions is the gateway's generated configuration with extra
// appended to it. Named, rather than inlined in Run, so a service's tests can
// build the same mux the server runs — gatewayMuxOptions(config.ServeMuxOptions...)
// — instead of a copy of the option list that drifts from it.
//
// Order is the contract: grpc-gateway applies options in sequence, so a
// Configuration.ServeMuxOptions entry that sets one value (an error handler, a
// header matcher) replaces the generated default, while one that accumulates
// (an annotator, a forward-response option) runs after the generated ones.
func gatewayMuxOptions(extra ...runtime.ServeMuxOption) []runtime.ServeMuxOption {
	options := []runtime.ServeMuxOption{
		runtime.WithMetadata(CustomHeaderToGRPCMetadataAnnotator),
		runtime.WithErrorHandler(customErrorHandler),
	}
	return append(options, extra...)
}

func (s *RestServer) Run(ctx context.Context) error {
	fmt.Println("Starting Rest server at", *s.config.EndpointHttpPort)

	// Create a CORS handler
	c := Cors()

	gwMux := runtime.NewServeMux(gatewayMuxOptions(s.config.ServeMuxOptions...)...)

	// Register generated gateway handlers

	opts := []grpc.DialOption{grpc.WithTransportCredentials(insecure.NewCredentials())}

	err := gen.RegisterWebServiceHandlerFromEndpoint(ctx, gwMux, fmt.Sprintf("0.0.0.0:%d", s.config.EndpointGrpcPort), opts)
	if err != nil {
		return err
	}

	// Register plugin REST handlers
	for _, p := range plugins.All() {
		if err := p.RegisterREST(ctx, gwMux, fmt.Sprintf("0.0.0.0:%d", s.config.EndpointGrpcPort), opts); err != nil {
			return fmt.Errorf("plugin %s REST registration failed: %w", p.Name(), err)
		}
	}

	// Expose the gRPC health check as /healthz for HTTP probes
	healthConn, err := grpc.NewClient(fmt.Sprintf("0.0.0.0:%d", s.config.EndpointGrpcPort), opts...)
	if err != nil {
		return fmt.Errorf("failed to create health client connection: %w", err)
	}
	healthClient := grpc_health_v1.NewHealthClient(healthConn)
	err = gwMux.HandlePath(http.MethodGet, "/healthz", func(w http.ResponseWriter, r *http.Request, _ map[string]string) {
		resp, err := healthClient.Check(r.Context(), &grpc_health_v1.HealthCheckRequest{})
		if err != nil || resp.GetStatus() != grpc_health_v1.HealthCheckResponse_SERVING {
			http.Error(w, `{"status":"NOT_SERVING"}`, http.StatusServiceUnavailable)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"status":"SERVING"}`))
	})
	if err != nil {
		return fmt.Errorf("failed to register health check handler: %w", err)
	}

	// Wrap the service's own routes and the gateway with the CORS handler
	handler := c.Handler(WithRoutes(s.config.Routes, gwMux))

	s.server.Handler = logRequestBody(handler)
	if err := s.server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		return err
	}
	return nil
}

func (s *RestServer) Shutdown(ctx context.Context) error {
	return s.server.Shutdown(ctx)
}

// Route is one HTTP handler served on the REST listener under a path prefix,
// as named in Configuration.Routes.
type Route struct {
	Prefix  string
	Handler http.Handler
}

// WithRoutes serves each route's prefix with its handler and everything else
// with next. First match wins, by plain prefix rather than through an
// http.ServeMux in front of the gateway: a ServeMux cleans and redirects paths,
// which would change how the gateway answers a path it already serves.
func WithRoutes(routes []Route, next http.Handler) http.Handler {
	if len(routes) == 0 {
		return next
	}
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		for _, route := range routes {
			if strings.HasPrefix(r.URL.Path, route.Prefix) {
				route.Handler.ServeHTTP(w, r)
				return
			}
		}
		next.ServeHTTP(w, r)
	})
}

type logResponseWriter struct {
	http.ResponseWriter
	statusCode int
}

func (rsp *logResponseWriter) WriteHeader(code int) {
	rsp.statusCode = code
	rsp.ResponseWriter.WriteHeader(code)
}

// Unwrap returns the original http.ResponseWriter. This is necessary
// to expose Flush() and Push() on the underlying response writer.
func (rsp *logResponseWriter) Unwrap() http.ResponseWriter {
	return rsp.ResponseWriter
}

func newLogResponseWriter(w http.ResponseWriter) *logResponseWriter {
	return &logResponseWriter{w, http.StatusOK}
}

// logRequestBody logs the request body when the response status code is not 200.
func logRequestBody(h http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		lw := newLogResponseWriter(w)

		// Note that buffering the entire request body could consume a lot of memory.
		body, err := io.ReadAll(r.Body)
		if err != nil {
			http.Error(w, fmt.Sprintf("failed to read body: %v", err), http.StatusBadRequest)
			return
		}
		clonedR := r.Clone(r.Context())
		clonedR.Body = io.NopCloser(bytes.NewReader(body))

		h.ServeHTTP(lw, clonedR)

		if lw.statusCode != http.StatusOK {
			grpclog.Errorf("http error %+v request body %+v", lw.statusCode, string(body))
		}
	})
}
