package adapters

/* -----------------------------------------------------------------

⚠️ This code is generated by the agent. Do not edit this file!


----------------------------------------------------------------- */

import (
	"codefly-base/plugins"
	"context"
	"fmt"
	"time"
)

type Server struct {
	grpc    *GrpcServer
	rest    *RestServer
	connect *ConnectServer
}

func NewServer(config *Configuration) (*Server, error) {

	grpc, err := NewGrpServer(config)
	if err != nil {
		return nil, err
	}

	// Register plugins on the gRPC server
	for _, p := range plugins.All() {
		p.RegisterGRPC(grpc.gRPC)
	}

	var rest *RestServer
	if config.EndpointHttpPort != nil {
		rest, err = NewRestServer(config)
		if err != nil {
			return nil, err
		}
	}

	// Built last on purpose: the Connect listener transcodes to this same gRPC
	// server, and routes the services registered on it by now — the scaffolded
	// service and every plugin above.
	var conn *ConnectServer
	if config.EndpointConnectPort != nil {
		conn, err = NewConnectServer(config, grpc.gRPC)
		if err != nil {
			return nil, err
		}
	}

	return &Server{
		grpc:    grpc,
		rest:    rest,
		connect: conn,
	}, nil
}

func (server *Server) Start(ctx context.Context) error {
	if server.rest != nil {
		go func() {
			err := server.rest.Run(ctx)
			if err != nil {
				panic(err)
			}
		}()
	}
	if server.connect != nil {
		go func() {
			err := server.connect.Run(ctx)
			if err != nil {
				panic(err)
			}
		}()
	}
	return server.grpc.Run(ctx)
}

func (server *Server) Stop() {
	fmt.Println("Stopping server...")
	if server.rest != nil {
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		if err := server.rest.Shutdown(ctx); err != nil {
			fmt.Printf("failed to stop REST server: %v\n", err)
		}
		cancel()
	}
	if server.connect != nil {
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		if err := server.connect.Shutdown(ctx); err != nil {
			fmt.Printf("failed to stop Connect server: %v\n", err)
		}
		cancel()
	}
	server.grpc.health.Shutdown()
	server.grpc.gRPC.GracefulStop()
}
