package adapters

/* -----------------------------------------------------------------

⚠️ This code is generated by the agent. Do not edit this file!


----------------------------------------------------------------- */

import (
	"codefly-base/plugins"
	"context"
	"fmt"
)

type Server struct {
	grpc    *GrpcServer
	rest    *RestServer
	connect *ConnectServer
}

func NewServer(config *Configuration) (*Server, error) {

	grpc, err := NewGrpServer(config)
	if err != nil {
		return nil, err
	}

	// Register plugins on the gRPC server
	for _, p := range plugins.All() {
		p.RegisterGRPC(grpc.gRPC)
	}

	var rest *RestServer
	if config.EndpointHttpPort != nil {
		rest, err = NewRestServer(config)
		if err != nil {
			return nil, err
		}
	}

	var conn *ConnectServer
	if config.EndpointConnectPort != nil {
		conn, err = NewConnectServer(config)
		if err != nil {
			return nil, err
		}
	}

	return &Server{
		grpc:    grpc,
		rest:    rest,
		connect: conn,
	}, nil
}

func (server *Server) Start(ctx context.Context) error {
	if server.rest != nil {
		go func() {
			err := server.rest.Run(ctx)
			if err != nil {
				panic(err)
			}
		}()
	}
	if server.connect != nil {
		go func() {
			err := server.connect.Run(ctx)
			if err != nil {
				panic(err)
			}
		}()
	}
	return server.grpc.Run(ctx)
}

func (server *Server) Stop() {
	fmt.Println("Stopping server...")
	server.grpc.gRPC.GracefulStop()
}
